In [1]:
import tensorflow as tf 
import numpy as np 
import sys
from pathlib import Path
from os.path import dirname, abspath
script_dir = Path(dirname(abspath('')))
module_dir = str(script_dir)
sys.path.insert(0, module_dir + '/modules')
sys.path.insert(0, module_dir + '/models')
print(module_dir)
import sde_evolve as se
import drift
import sim

C:\Users\pinak\Documents\GitHub\symmertic_attractor


In [14]:
X0 = np.random.multivariate_normal([0., 0., 0.], np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]), 1000000)
mc = sim.MCProb(save_folder='../data', n_subdivs=30, mu=drift.mu_np, sigma=0.5, X0=X0)
mc.ready(n_steps=50, dt=0.1, lims=None)
mc.slice2D(dims=[0, 2], levels={1: 0.})

Time taken by propagate is 11.993975639343262 seconds
Time taken by set_grid is 4.936173677444458 seconds
Time taken by assign_pts is 5.355733633041382 seconds
Time taken by ready is 22.2858829498291 seconds
Time taken by get_slice_pts is 4.335223197937012 seconds
Time taken by slice2D is 4.4908905029296875 seconds


In [3]:
mc.slice2D(dims=[1, 2], levels={0: 0.})

Time taken by get_slice_pts is 4.424594402313232 seconds
Time taken by slice2D is 4.592176675796509 seconds


In [4]:
mc.slice2D(dims=[0, 1], levels={2: 0.})

Time taken by get_slice_pts is 4.433797836303711 seconds
Time taken by slice2D is 4.582354545593262 seconds


In [5]:
X0 = np.random.multivariate_normal([0., 0., 0.], [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]], 100000)

In [6]:
print(X0)

[[ 0.41311008  1.74930116  0.94029348]
 [ 0.07342428  0.94161813 -0.47198109]
 [-1.18043604 -0.06654274 -0.65104864]
 ...
 [-0.42493936 -0.62992098 -1.02032755]
 [-0.32457681  0.51269831  2.69886703]
 [ 0.20970109 -1.30931124 -0.03641359]]
